In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("archive/Music Info.csv")
df2 = pd.read_csv("archive/User Listening History.csv")

In [3]:
df1.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4,"rock, alternative, indie, alternative_rock, in...",NaN,2004,237026,0.279,...,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 50683 entries, 0 to 50682
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_id             50683 non-null  str
 1   name                 50683 non-null  str
 2   artist               50683 non-null  str
 3   spotify_preview_url  50683 non-null  str
 4   spotify_id           50683 non-null  str
 5   tags                 49556 non-null  str
 6   genre                22348 non-null  str
 7   year                 50683 non-null  int64
 8   duration_ms          50683 non-null  int64
 9   danceability         50683 non-null  float64
 10  energy               50683 non-null  float64
 11  key                  50683 non-null  int64
 12  loudness             50683 non-null  float64
 13  mode                 50683 non-null  int64
 14  speechiness          50683 non-null  float64
 15  acousticness         50683 non-null  float64
 16  instrumentalness     50683 non-null  float64
 17  liveness             50683 non-null  float64
 18  valence              50683 non-null  float64
 19  tempo                50683 non-null  float64
 20  time_signature       50683 non-null  int64
dtypes: float64(9), int64(5), str(7)
memory usage: 8.1 MB

In [3]:
df1 = df1.drop(columns=["spotify_preview_url",'spotify_id','genre','key','loudness','mode','speechiness','acousticness','valence','tempo','time_signature'])
df1.head()

,track_id,name,artist,tags,year,duration_ms,danceability,energy,instrumentalness,liveness
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,0.000000,0.0971
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,0.000000,0.2070
2,TROUVHL128F426C441,Come as You Are,Nirvana,"rock, alternative, alternative_rock, 90s, grunge",1991,218920,0.508,0.826,0.000459,0.0878
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",2004,237026,0.279,0.664,0.000655,0.1330
4,TRLNZBD128F935E4D8,Creep,Radiohead,"rock, alternative, indie, alternative_rock, in...",2008,238640,0.515,0.430,0.000141,0.1290

In [4]:
print(len(df1["artist"].str.strip().str.casefold().unique()))
print(len(df1["artist"].unique()))
print(len(df1["name"].str.strip().str.casefold().unique()))

8317
8317
49868

In [5]:
df2.groupby("track_id").playcount.agg('sum').sort_values(ascending=False).head(25)

track_id
TRONYHY128F92C9D11    527893
TRUFTBY128F93450B8    111615
TRZNAHL128F9327D5A    111596
TRCPXID128F92D5D3C     91461
TRPGPDK12903CCC651     91448
TRXWAZC128F9314B3E     87745
TROMKCG128F9320C09     87050
TRPFYYL128F92F7144     85079
TRGCHLH12903CB7352     78443
TRAALAH128E078234A     76893
TRWAQOC12903CB84CA     72259
TRBNYBX128F422EC61     66852
TRLVQME128F931BAF3     63937
TRSUSWW128F93463BF     62438
TRRVJCK12903CD2DCB     61568
TRABFDT12903CADD73     59810
TRCRCBT128F4260DD1     58059
TRHNBHR128F9350E67     57178
TRWVOJJ12903CCC654     55655
TRCKWGF12903CD2DCD     54149
TRAOIAH128F92F707B     52472
TRZALGW128F4296174     51280
TRXUWEC128F426BE3F     49649
TRFTUIW128E0784B9F     49597
TRJJCJQ12903CD2DD3     49119
Name: playcount, dtype: int64

In [6]:
len(df2.groupby("track_id").playcount.agg('sum').sort_values(ascending=False))

30459

In [7]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 9711301 entries, 0 to 9711300
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   track_id   str
 1   user_id    str
 2   playcount  int64
dtypes: int64(1), str(2)
memory usage: 222.3 MB

In [8]:
c = df1["track_id"].isin(df2["track_id"]).sum()
print(c)

30459

In [9]:
df2.loc[df2.track_id == "TRJJCJQ12903CD2DD3"]

,track_id,user_id,playcount
487,TRJJCJQ12903CD2DD3,a58de017cbeda1763ea002fe027ed41b4ed53109,3
637,TRJJCJQ12903CD2DD3,930d2be6c85315d72cab9823ec0f7bfe7e477794,1
738,TRJJCJQ12903CD2DD3,b6b799f34a204bd928ea014c243ddad6d0be4f8f,3
1680,TRJJCJQ12903CD2DD3,e4e99e5b3223bec258cf2ff0d090d05a06302344,5
2071,TRJJCJQ12903CD2DD3,4691b4c353503da2c108e372ff056a9ac847c4d1,6
...,...,...,...
9709080,TRJJCJQ12903CD2DD3,1c2899e2a224860f51822b1ef3d232fa7c87a912,9
9709251,TRJJCJQ12903CD2DD3,eb7927c723311ccb1958749aae9562a81dfda7e3,1
9709363,TRJJCJQ12903CD2DD3,068ac30b851c3bfff876e26444fd12793b293e77,1
9710434,TRJJCJQ12903CD2DD3,e99a4bfdeffec9434d17ee24d7f4e55b6c723280,1
9711242,TRJJCJQ12903CD2DD3,8305c896f42308824da7d4386f4b9ee584281412,4

In [10]:
import pandas as pd

# df2 columns assumed: user_id, track_id, play_count

song_stats = (
    df2.groupby('track_id')
       .agg(
           total_playcount=('playcount', 'sum'),
           n_users=('user_id', 'nunique')
       )
       .reset_index()
)

song_stats['freq'] = song_stats['total_playcount'] / song_stats['n_users']

song_stats = song_stats.sort_values('total_playcount', ascending=False)

song_stats = song_stats[song_stats['n_users'] > 5]
song_stats

                 track_id  total_playcount  n_users      freq
17456  TRONYHY128F92C9D11           527893    80656  6.544994
23756  TRUFTBY128F93450B8           111615    39529  2.823623
30000  TRZNAHL128F9327D5A           111596    24592  4.537899
3129   TRCPXID128F92D5D3C            91461    30057  3.042918
18456  TRPGPDK12903CCC651            91448    27276  3.352691
...                   ...              ...      ...       ...
25132  TRVDTRM128F1491225                6        6  1.000000
11     TRAACZR12903CDD291                6        6  1.000000
27914  TRXRAWI128F14AC12B                6        6  1.000000
8071   TRGIZVR12903CDAFD4                6        6  1.000000
8619   TRGUUJG128EF34C577                6        6  1.000000

[26364 rows x 4 columns]

In [11]:
df = pd.merge(df1, song_stats, on='track_id', how='inner')
print(df.shape)
df

(26364, 13)

,track_id,name,artist,tags,year,duration_ms,danceability,energy,instrumentalness,liveness,total_playcount,n_users,freq
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,0.000000,0.0971,162,41,3.951220
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,0.000000,0.2070,995,378,2.632275
2,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",2004,237026,0.279,0.664,0.000655,0.1330,21,20,1.050000
3,TRUJIIV12903CA8848,Clocks,Coldplay,"rock, alternative, indie, pop, alternative_roc...",2002,307879,0.577,0.749,0.011500,0.1830,11,7,1.571429
4,TRIODZU128E078F3E2,Under the Bridge,Red Hot Chili Peppers,"rock, alternative, alternative_rock, 90s, funk",2003,265506,0.554,0.490,0.000534,0.1360,990,393,2.519084
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26359,TRMEHFD128F92E4557,The Revenge of Surf Queen,9mm Parabellum Bullet,"rock, instrumental, japanese",2008,181560,0.337,0.980,0.916000,0.0991,42,13,3.230769
26360,TRXWSIN128F9339A11,Infinite Love Song,Maximilian Hecker,"electronic, indie_pop, love",2002,285800,0.549,0.675,0.437000,0.1220,36,10,3.600000
26361,TRPIGDW12903CDEB2D,Slip of the Lip,Fact,"alternative_rock, punk_rock",2010,183640,0.423,0.980,0.000002,0.3790,93,23,4.043478
26362,TRHQCSH128F42724B7,Colors Of The Wind,ACIDMAN,"rock, alternative_rock, japanese, cover",2004,275133,0.351,0.693,0.000049,0.1920,37,13,2.846154
26363,TRGLMEM128F9322F63,Koi no Dependence,アンティック-珈琲店-,NaN,2008,243293,0.513,0.902,0.001350,0.0571,40,11,3.636364

In [12]:
df.isnull().sum()

track_id              0
name                  0
artist                0
tags                572
year                  0
duration_ms           0
danceability          0
energy                0
instrumentalness      0
liveness              0
total_playcount       0
n_users               0
freq                  0
dtype: int64

In [13]:
df["tags"] = df["tags"].fillna("non")
df.isnull().sum()

track_id            0
name                0
artist              0
tags                0
year                0
duration_ms         0
danceability        0
energy              0
instrumentalness    0
liveness            0
total_playcount     0
n_users             0
freq                0
dtype: int64

In [18]:
df = df.drop(columns=["total_playcount","n_users","freq"])
df.info()

KeyError: "['total_playcount', 'n_users', 'freq'] not found in axis"

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26364 entries, 0 to 26363
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_id          26364 non-null  str
 1   name              26364 non-null  str
 2   artist            26364 non-null  str
 3   tags              26364 non-null  str
 4   year              26364 non-null  float64
 5   duration_ms       26364 non-null  float64
 6   danceability      26364 non-null  float64
 7   energy            26364 non-null  float64
 8   instrumentalness  26364 non-null  float64
 9   liveness          26364 non-null  float64
dtypes: float64(6), str(4)
memory usage: 2.0 MB

In [25]:
from sklearn.preprocessing import MinMaxScaler

numeric_cols = df.select_dtypes(include="number").columns

scaler = MinMaxScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [26]:
df.to_csv("initial_data.csv")

In [27]:
print(len(df2["user_id"].unique()))
print(df2.shape)

962037
(9711301, 3)

In [28]:
df2.groupby("user_id").user_id.agg("count").sort_values(ascending=False)

user_id
ec6dfcf19485cb011e0b22637075037aae34cf26    784
4e11f45d732f4861772b2906f81a7d384552ad12    384
726da71c2c2ea119119a7957517fccd028d1be76    376
113255a012b2affeab62607563d03fbdf31b08e7    367
7adec7f006cb09482d36609d205293d8b61f030e    366
                                           ...
0002236e33c94f6d300fa52a045e0c7ae1e19ccf      1
8e7549d9924e0d4b0219a04bdb69e7c8d6c06de3      1
8e7530b08d2639c56f36646d50ef3e0af5d0c02a      1
8e751f160963aeef7f47bd542214a7ad6a029fd5      1
fffcecd0d67e9bede07660fbaf6ca43b1857a75c      1
Name: user_id, Length: 962037, dtype: int64

In [29]:
df2 = df2[df2.groupby("user_id")["user_id"].transform("size") > 1]
user_char = df2.sort_values(by=["user_id","playcount"],ascending=False)
user_char

,track_id,user_id,playcount
6279529,TRLHPYP128F4259AB7,fffff9534445f481b6ab91c345500083d2ce4df1,20
6279532,TRONYHY128F92C9D11,fffff9534445f481b6ab91c345500083d2ce4df1,10
6279526,TRARTPH128E0789C05,fffff9534445f481b6ab91c345500083d2ce4df1,1
6279527,TRLSCIQ12903CFDBEE,fffff9534445f481b6ab91c345500083d2ce4df1,1
6279528,TRGZRNJ128F92F4139,fffff9534445f481b6ab91c345500083d2ce4df1,1
...,...,...,...
1831363,TRIYKXW128F92FDF08,00001cf0dce3fb22b0df0f3a1d9cd21e38385372,2
1831366,TREZYWT128F93191B7,00001cf0dce3fb22b0df0f3a1d9cd21e38385372,2
1831361,TRGEIDA128F933B4B8,00001cf0dce3fb22b0df0f3a1d9cd21e38385372,1
1831364,TRVRIBZ128F426BF71,00001cf0dce3fb22b0df0f3a1d9cd21e38385372,1
1831365,TRPUGUW128F426BF6F,00001cf0dce3fb22b0df0f3a1d9cd21e38385372,1

In [30]:
user_char.to_csv("user_char.csv")